import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react';
import Popup from '@/components/popup';
import Script from 'next/script';
const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  const [paymentURL, setPaymentURL] = useState(null)
  async function makePayment(ev) {
    ev.preventDefault();
    const submitButton = ev.target.querySelector("button[type='submit']")
    submitButton.disabled = true;
    const email = new FormData(ev.target).get("email")
    const mpResponse = await fetch("/api/payment", {
      method: "POST",
      headers: {
        type: "application/json"
      },
      body: JSON.stringify({ email })
    })
      .then(response => response.json())
      .catch(err => console.error(err));
    if (mpResponse) {
      setPaymentURL(mpResponse.init_point)
    }
    submitButton.disabled = false;
  }
  return (
    <>
      <Head>
        <title>Página de prueba Mercado Pago</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <form onSubmit={makePayment} className={styles.form}>
          <input type="email" name='email' placeholder='Ingrese E-mail' className={styles.formInput} />
          <button type='submit' className={styles.formSubmit}>
            ENVIAR
          </button>
        </form>
      </main>
      <Popup path={paymentURL} updatePath={setPaymentURL} />
      <Script src="https://sdk.mercadopago.com/js/v2" strategy='afterInteractive' />
    </>
  )
}
